from collections import defaultdict

BOT_ACCOUNT: int = 0
BOT_HOST: str = ""
AUTHKEY: str = ""
MYSQL_HOST: str = ""
MYSQL_PORT: str = ""
MYSQL_USER: str = ""
MYSQL_PASSWORD: str = ""
MYSQL_DDL_DB: str = ""
MYSQL_DDL_TABLE: str = ""
SETU_API_KEY: str = ""
SETU_ENABLED_GROUPS: set = set()
ADMIN_QQ: int = 0
LEETCODE_ENABLED_GROUPS: set = set()
BILIBILI_SUBSCRIBE_SETTINGS: dict = defaultdict(set)
STEAM_API_KEY: str = ""
BAIDU_TRANSLATE_APP_ID: str = ""
BAIDU_TRANSLATE_SECRET_KEY: str = ""
